---
- name: Export job_templates
  ansible.controller.export:
    controller_host: "{{ source_aap_hostname }}"
    controller_password: "{{ source_aap_password }}"
    controller_username: "{{ source_aap_username }}"
    validate_certs: "{{ source_aap_validate_certs }}"
    job_templates: "{{ item }}"
  loop: "{{ job_templates }}"
  register: exported_job_templates

- name: Import job_templates
  ansible.controller.import:
    controller_host: "{{ target_aap_hostname }}"
    controller_password: "{{ target_aap_password }}"
    controller_username: "{{ target_aap_username }}"
    validate_certs: "{{ target_aap_validate_certs }}"
    assets: "{{ item.assets }}"
  loop: "{{ exported_job_templates.results }}"
