---
- name: Export Notification Templates
  ansible.controller.export:
    controller_host: "{{ source_aap_hostname }}"
    controller_password: "{{ source_aap_password }}"
    controller_username: "{{ source_aap_username }}"
    validate_certs: "{{ source_aap_validate_certs }}"
    notification_templates: "{{ item }}"
  loop: "{{ notification_templates }}"
  register: exported_notification_templates

- name: Import Notifications Templates
  ansible.controller.import:
    controller_host: "{{ target_aap_hostname }}"
    controller_password: "{{ target_aap_password }}"
    controller_username: "{{ target_aap_username }}"
    validate_certs: "{{ target_aap_validate_certs }}"
    assets: "{{ item.assets }}"
  loop: "{{ exported_notification_templates.results }}"