---
- name: Export organizations
  ansible.controller.export:
    controller_host: "{{ source_aap_hostname }}"
    controller_password: "{{ source_aap_password }}"
    controller_username: "{{ source_aap_username }}"
    validate_certs: "{{ source_aap_validate_certs }}"
    organizations: "{{ item }}"
  loop: "{{ organizations }}"
  register: exported_organizations

- name: Import organizations
  ansible.controller.import:
    controller_host: "{{ target_aap_hostname }}"
    controller_password: "{{ target_aap_password }}"
    controller_username: "{{ target_aap_username }}"
    validate_certs: "{{ target_aap_validate_certs }}"
    assets: "{{ item.assets }}"
  loop: "{{ exported_organizations.results }}"